attempt to correct JSON parsing error
This seeks to correct...

```
=== RUN   TestAccAnnotation_basic

    resource_annotation_test.go:24: Step 7/9 error: Error running apply: exit status 1

        Error: Unsupported attribute

          on terraform_plugin_test.tf line 19, in locals:

          19:   panel_id       = local.dashboard_json.dashboard.panels[0].id

            ├────────────────

            │ local.dashboard_json is object with 5 attributes

        This object does not have an attribute named "dashboard".
```

Signed-off-by: Mike Ball <mikedball@gmail.com>