Bump github.com/grafana/synthetic-monitoring-agent from 0.25.2 to 0.28.0 (#1813)
* Bump github.com/grafana/synthetic-monitoring-agent from 0.25.2 to 0.28.0

Bumps [github.com/grafana/synthetic-monitoring-agent](https://github.com/grafana/synthetic-monitoring-agent) from 0.25.2 to 0.28.0.
- [Release notes](https://github.com/grafana/synthetic-monitoring-agent/releases)
- [Changelog](https://github.com/grafana/synthetic-monitoring-agent/blob/main/CHANGELOG.md)
- [Commits](https://github.com/grafana/synthetic-monitoring-agent/compare/v0.25.2...v0.28.0)

---
updated-dependencies:
- dependency-name: github.com/grafana/synthetic-monitoring-agent
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* rever go/toolchain versioning

* fix(lint): ensure golangci-lint works with go1.23 and fix lint errors

* chore: disable gosec(G115)

Ignoring this rule as this doesn't break anything but causes lint errors.

Upstream ref: https://github.com/securego/gosec/issues/1185

* test: fix test throwing 'addDataSourceConflict {"message":"data source with the same name already exists"}'

I can't get this test to work, I've tried:
- Replacing ParallelTest() with just Test()
- Replacing 'foo' with a random string

I keep getting this:

```
=== RUN   TestAccResourceJob
    resource_job_test.go:23: Step 1/3 error: Error running apply: exit status 1

        Error: [POST /datasources][409] addDataSourceConflict {"message":"data source with the same name already exists"}

          with grafana_data_source.foo,
          on terraform_plugin_test.tf line 1, in resource "grafana_data_source" "foo":
           1: resource "grafana_data_source" "foo" {

--- FAIL: TestAccResourceJob (1.26s)
```

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Duologic <jeroen@simplistic.be>