add initial, basic grafana_annotation resource (#558)
* add initial, basic grafana_annotation resource

This seeks to address issue #11

Signed-off-by: Mike Ball <mikedball@gmail.com>

* appease golangci-lint

Signed-off-by: Mike Ball <mikedball@gmail.com>

* convert set to string slice

Signed-off-by: Mike Ball <mikedball@gmail.com>

* error if API returns no annotations

Signed-off-by: Mike Ball <mikedball@gmail.com>

* correct annotation destroy check test logic

Signed-off-by: Mike Ball <mikedball@gmail.com>

* test grafana_annotation update scenario

Signed-off-by: Mike Ball <mikedball@gmail.com>

* grafana annotation text is required

Signed-off-by: Mike Ball <mikedball@gmail.com>

* simplify annotation resource test logic

Signed-off-by: Mike Ball <mikedball@gmail.com>

* build trigger

* remove incompatible default setting

This seeks to fix...

```
* resource grafana_annotation: text: Default cannot be set with Required
```

Signed-off-by: Mike Ball <mikedball@gmail.com>

* fix docs drift

Signed-off-by: Mike Ball <mikedball@gmail.com>

* remove copy/pasta defaults

Signed-off-by: Mike Ball <mikedball@gmail.com>

* update annotation documentation

Signed-off-by: Mike Ball <mikedball@gmail.com>

* add time/time_end arguments to annotation

Signed-off-by: Mike Ball <mikedball@gmail.com>

* update annotation documentation w/ time/time_end

Signed-off-by: Mike Ball <mikedball@gmail.com>

* acceptance test annotation w/ dashboard_id

Signed-off-by: Mike Ball <mikedball@gmail.com>

* force new annotation w/ dashboard_id/panel_id change

Signed-off-by: Mike Ball <mikedball@gmail.com>

* uniquely/consistently name annotation test resources

Signed-off-by: Mike Ball <mikedball@gmail.com>

* acceptance test annotation w/ panel_id argument

Signed-off-by: Mike Ball <mikedball@gmail.com>

* use data source to retrieve dashboard JSON

Signed-off-by: Mike Ball <mikedball@gmail.com>

* attempt to correct JSON parsing error

This seeks to correct...

```
=== RUN   TestAccAnnotation_basic

    resource_annotation_test.go:24: Step 7/9 error: Error running apply: exit status 1

        Error: Unsupported attribute

          on terraform_plugin_test.tf line 19, in locals:

          19:   panel_id       = local.dashboard_json.dashboard.panels[0].id

            ├────────────────

            │ local.dashboard_json is object with 5 attributes

        This object does not have an attribute named "dashboard".
```

Signed-off-by: Mike Ball <mikedball@gmail.com>

* explicitly set panel ID in annotation test

Signed-off-by: Mike Ball <mikedball@gmail.com>

* remove use of data source in annotion test

Signed-off-by: Mike Ball <mikedball@gmail.com>

* Revert "remove use of data source in annotion test"

This reverts commit 969d36ab5ffd44734a08cc7349dcf66cbb37aad7.

* build trigger

* build trigger